import Foundation

func capabilityRows() -> [[String: Any]] {
    let oauth1PreferredStatus = "swift-oauth1-preferred-bearer-fallback"
    let appBearerPreferredStatus = "swift-app-bearer-preferred"
    let bearerStatus = "swift-bearer-baseline"
    return [
        capabilityRow(id: "account.me", operation: "accountMe", access: "read", status: oauth1PreferredStatus),
        capabilityRow(id: "user.get", operation: "user", access: "read", status: oauth1PreferredStatus),
        capabilityRow(id: "user.getByUsername", operation: "userByUsername", access: "read", status: oauth1PreferredStatus),
        capabilityRow(id: "user.batch.get", operation: "users", access: "read", status: oauth1PreferredStatus),
        capabilityRow(id: "user.batch.getByUsername", operation: "usersByUsernames", access: "read", status: oauth1PreferredStatus),
        capabilityRow(id: "user.followers", operation: "followers", access: "read", status: oauth1PreferredStatus),
        capabilityRow(id: "user.following", operation: "following", access: "read", status: oauth1PreferredStatus),
        capabilityRow(id: "user.muting", operation: "mutedUsers", access: "read", status: bearerStatus),
        capabilityRow(id: "user.blocking", operation: "blockedUsers", access: "read", status: bearerStatus),
        capabilityRow(id: "usage.tweets", operation: "apiUsage", access: "read", status: bearerStatus),
        capabilityRow(id: "timeline.following", operation: "followingTimeline", access: "read", status: oauth1PreferredStatus),
        capabilityRow(id: "post.get", operation: "post", access: "read", status: oauth1PreferredStatus),
        capabilityRow(id: "post.batch.get", operation: "posts", access: "read", status: oauth1PreferredStatus),
        capabilityRow(id: "post.likedByUser", operation: "likedPosts", access: "read", status: bearerStatus),
        capabilityRow(id: "post.replies", operation: "Post.replies", access: "read", status: oauth1PreferredStatus),
        capabilityRow(id: "post.likingUsers", operation: "postLikingUsers", access: "read", status: oauth1PreferredStatus),
        capabilityRow(id: "post.repostingUsers", operation: "postRepostingUsers", access: "read", status: oauth1PreferredStatus),
        capabilityRow(id: "post.quotes", operation: "postQuotes", access: "read", status: oauth1PreferredStatus),
        capabilityRow(id: "search.posts.all", operation: "searchAllPosts", access: "read", status: appBearerPreferredStatus),
        capabilityRow(id: "search.users", operation: "searchUsers", access: "read", status: bearerStatus),
        capabilityRow(id: "search.news", operation: "searchNews", access: "read", status: bearerStatus),
        capabilityRow(id: "news.get", operation: "news", access: "read", status: bearerStatus),
        capabilityRow(id: "trends.woeid", operation: "trendsByWoeid", access: "read", status: bearerStatus),
        capabilityRow(id: "post.counts.recent", operation: "recentPostCounts", access: "read", status: appBearerPreferredStatus),
        capabilityRow(id: "bookmarks.list", operation: "bookmarks", access: "read", status: bearerStatus),
        capabilityRow(id: "bookmarks.folders.list", operation: "bookmarkFolders", access: "read", status: bearerStatus),
        capabilityRow(id: "bookmarks.folders.posts", operation: "bookmarksByFolder", access: "read", status: bearerStatus),
        capabilityRow(id: "lists.get", operation: "list", access: "read", status: bearerStatus),
        capabilityRow(id: "lists.owned", operation: "ownedLists", access: "read", status: bearerStatus),
        capabilityRow(id: "lists.followed", operation: "followedLists", access: "read", status: bearerStatus),
        capabilityRow(id: "lists.memberships", operation: "listMemberships", access: "read", status: bearerStatus),
        capabilityRow(id: "lists.pinned", operation: "pinnedLists", access: "read", status: bearerStatus),
        capabilityRow(id: "lists.followers", operation: "listFollowers", access: "read", status: bearerStatus),
        capabilityRow(id: "lists.members", operation: "listMembers", access: "read", status: bearerStatus),
        capabilityRow(id: "lists.posts", operation: "listPosts", access: "read", status: bearerStatus),
        capabilityRow(id: "dm.events", operation: "dmEvents", access: "read", status: bearerStatus),
        capabilityRow(id: "dm.event", operation: "dmEvent", access: "read", status: bearerStatus),
        capabilityRow(id: "dm.conversation.events", operation: "dmConversationEvents", access: "read", status: bearerStatus),
        capabilityRow(id: "dm.conversation.eventsById", operation: "dmConversationEventsById", access: "read", status: bearerStatus),
        capabilityRow(id: "timeline.search", operation: "searchPosts", access: "read", status: oauth1PreferredStatus),
        capabilityRow(id: "timeline.user", operation: "userTimeline", access: "read", status: oauth1PreferredStatus),
        capabilityRow(id: "timeline.home", operation: "homeTimeline", access: "read", status: oauth1PreferredStatus),
        capabilityRow(id: "timeline.mentions", operation: "mentionsTimeline", access: "read", status: oauth1PreferredStatus),
        capabilityRow(id: "post.create", operation: "createPost", access: "write", status: oauth1PreferredStatus),
        capabilityRow(id: "post.delete", operation: "deletePost", access: "write", status: oauth1PreferredStatus),
        capabilityRow(id: "post.reply", operation: "replyToPost", access: "write", status: oauth1PreferredStatus),
        capabilityRow(id: "post.quote", operation: "quotePost", access: "write", status: oauth1PreferredStatus),
        capabilityRow(id: "post.repost", operation: "repostPost", access: "write", status: oauth1PreferredStatus),
        capabilityRow(id: "post.unrepost", operation: "unrepostPost", access: "write", status: oauth1PreferredStatus),
        capabilityRow(id: "bookmarks.add", operation: "bookmarkPost", access: "write", status: bearerStatus),
        capabilityRow(id: "bookmarks.remove", operation: "removeBookmark", access: "write", status: bearerStatus),
        capabilityRow(id: "post.like", operation: "likePost", access: "write", status: bearerStatus),
        capabilityRow(id: "post.unlike", operation: "unlikePost", access: "write", status: bearerStatus),
        capabilityRow(id: "user.follow", operation: "followUser", access: "write", status: bearerStatus),
        capabilityRow(id: "user.unfollow", operation: "unfollowUser", access: "write", status: bearerStatus),
        capabilityRow(id: "user.mute", operation: "muteUser", access: "write", status: bearerStatus),
        capabilityRow(id: "user.unmute", operation: "unmuteUser", access: "write", status: bearerStatus),
        capabilityRow(id: "lists.create", operation: "createList", access: "write", status: bearerStatus),
        capabilityRow(id: "lists.update", operation: "updateList", access: "write", status: bearerStatus),
        capabilityRow(id: "lists.delete", operation: "deleteList", access: "write", status: bearerStatus),
        capabilityRow(id: "lists.members.add", operation: "addListMember", access: "write", status: bearerStatus),
        capabilityRow(id: "lists.members.remove", operation: "removeListMember", access: "write", status: bearerStatus),
        capabilityRow(id: "lists.follow", operation: "followList", access: "write", status: bearerStatus),
        capabilityRow(id: "lists.unfollow", operation: "unfollowList", access: "write", status: bearerStatus),
        capabilityRow(id: "lists.pin", operation: "pinList", access: "write", status: bearerStatus),
        capabilityRow(id: "lists.unpin", operation: "unpinList", access: "write", status: bearerStatus),
        capabilityRow(id: "dm.create", operation: "createDirectMessage", access: "write", status: bearerStatus),
        capabilityRow(id: "dm.conversation.create", operation: "createDirectMessageConversation", access: "write", status: bearerStatus),
        capabilityRow(id: "dm.conversation.message.create", operation: "createDirectMessageInConversation", access: "write", status: bearerStatus),
        capabilityRow(id: "dm.delete", operation: "deleteDirectMessage", access: "write", status: bearerStatus),
        capabilityRow(id: "articles.draft.create", operation: "createArticleDraft", access: "write", status: oauth1PreferredStatus),
        capabilityRow(id: "articles.publish", operation: "publishArticle", access: "write", status: oauth1PreferredStatus),
        capabilityRow(id: "compliance.jobs.list", operation: "complianceJobs", access: "read", status: bearerStatus),
        capabilityRow(id: "compliance.jobs.get", operation: "complianceJob", access: "read", status: bearerStatus),
        capabilityRow(id: "compliance.jobs.create", operation: "createComplianceJob", access: "write", status: bearerStatus),
        capabilityRow(id: "communities.search", operation: "communitiesSearch", access: "read", status: bearerStatus),
        capabilityRow(id: "communities.get", operation: "community", access: "read", status: bearerStatus),
        capabilityRow(id: "community-notes.written", operation: "communityNotesWritten", access: "read", status: bearerStatus),
        capabilityRow(id: "community-notes.eligible-posts", operation: "communityPostsEligibleForNotes", access: "read", status: bearerStatus),
        capabilityRow(id: "community-notes.get", operation: "communityNote", access: "read", status: bearerStatus),
        capabilityRow(id: "community-notes.create", operation: "createCommunityNote", access: "write", status: bearerStatus),
        capabilityRow(id: "community-notes.delete", operation: "deleteCommunityNote", access: "write", status: bearerStatus),
        capabilityRow(id: "community-notes.evaluate", operation: "evaluateCommunityNote", access: "write", status: bearerStatus),
        capabilityRow(id: "analytics.posts", operation: "postAnalytics", access: "read", status: bearerStatus),
        capabilityRow(id: "post.reposts", operation: "postReposts", access: "read", status: bearerStatus),
        capabilityRow(id: "analytics.media", operation: "mediaAnalytics", access: "read", status: bearerStatus),
        capabilityRow(id: "insights.28hr", operation: "insights28hr", access: "read", status: bearerStatus),
        capabilityRow(id: "insights.historical", operation: "insightsHistorical", access: "read", status: bearerStatus),
        capabilityRow(id: "media.lookup", operation: "media", access: "read", status: bearerStatus),
        capabilityRow(id: "media.lookup.one", operation: "mediaByKey", access: "read", status: bearerStatus),
        capabilityRow(id: "media.upload.status", operation: "mediaUploadStatus", access: "read", status: bearerStatus),
        capabilityRow(id: "media.upload.oneshot", operation: "uploadMedia", access: "write", status: bearerStatus),
        capabilityRow(id: "media.upload.initialize", operation: "initializeMediaUpload", access: "write", status: bearerStatus),
        capabilityRow(id: "media.upload.append", operation: "appendMediaUpload", access: "write", status: bearerStatus),
        capabilityRow(id: "media.upload.finalize", operation: "finalizeMediaUpload", access: "write", status: bearerStatus),
        capabilityRow(id: "media.metadata.create", operation: "createMediaMetadata", access: "write", status: bearerStatus),
        capabilityRow(id: "media.subtitles.create", operation: "createMediaSubtitles", access: "write", status: bearerStatus),
        capabilityRow(id: "media.subtitles.delete", operation: "deleteMediaSubtitles", access: "write", status: bearerStatus),
        capabilityRow(id: "post.counts.all", operation: "allPostCounts", access: "read", status: appBearerPreferredStatus),
        capabilityRow(id: "post.hide-reply", operation: "hideReply", access: "write", status: bearerStatus),
        capabilityRow(id: "users.personalized-trends", operation: "personalizedTrends", access: "read", status: bearerStatus),
        capabilityRow(id: "users.public-keys", operation: "publicKeys", access: "read", status: bearerStatus),
        capabilityRow(id: "users.public-keys.one", operation: "userPublicKeys", access: "read", status: bearerStatus),
        capabilityRow(id: "users.public-keys.add", operation: "addUserPublicKey", access: "write", status: bearerStatus),
        capabilityRow(id: "users.affiliates", operation: "userAffiliates", access: "read", status: bearerStatus),
        capabilityRow(id: "users.reposts-of-me", operation: "repostsOfMe", access: "read", status: bearerStatus),
        capabilityRow(id: "dm.block", operation: "blockDirectMessages", access: "write", status: bearerStatus),
        capabilityRow(id: "dm.unblock", operation: "unblockDirectMessages", access: "write", status: bearerStatus),
        capabilityRow(id: "webhooks.list", operation: "webhooks", access: "read", status: bearerStatus),
        capabilityRow(id: "webhooks.create", operation: "createWebhook", access: "write", status: bearerStatus),
        capabilityRow(id: "webhooks.delete", operation: "deleteWebhook", access: "write", status: bearerStatus),
        capabilityRow(id: "webhooks.validate", operation: "validateWebhook", access: "write", status: bearerStatus),
        capabilityRow(id: "webhooks.replay", operation: "replayWebhook", access: "write", status: bearerStatus),
        capabilityRow(id: "activity.subscriptions.list", operation: "activitySubscriptions", access: "read", status: bearerStatus),
        capabilityRow(id: "activity.subscriptions.create", operation: "createActivitySubscription", access: "write", status: bearerStatus),
        capabilityRow(id: "activity.subscriptions.update", operation: "updateActivitySubscription", access: "write", status: bearerStatus),
        capabilityRow(id: "activity.subscriptions.delete", operation: "deleteActivitySubscription", access: "write", status: bearerStatus),
        capabilityRow(id: "activity.subscriptions.delete.bulk", operation: "deleteActivitySubscriptions", access: "write", status: bearerStatus),
        capabilityRow(id: "openapi.spec", operation: "openAPISpec", access: "read", status: appBearerPreferredStatus),
        capabilityRow(id: "account-activity.subscriptions.count", operation: "accountActivitySubscriptionCount", access: "read", status: bearerStatus),
        capabilityRow(id: "account-activity.subscriptions.list", operation: "accountActivitySubscriptions", access: "read", status: bearerStatus),
        capabilityRow(id: "account-activity.subscriptions.validate", operation: "validateAccountActivitySubscription", access: "read", status: bearerStatus),
        capabilityRow(id: "account-activity.subscriptions.create", operation: "createAccountActivitySubscription", access: "write", status: bearerStatus),
        capabilityRow(id: "account-activity.subscriptions.delete", operation: "deleteAccountActivitySubscription", access: "write", status: bearerStatus),
        capabilityRow(id: "chat.conversations.list", operation: "chatConversations", access: "read", status: bearerStatus),
        capabilityRow(id: "chat.conversations.get", operation: "chatConversation", access: "read", status: bearerStatus),
        capabilityRow(id: "chat.conversations.events", operation: "chatConversationEvents", access: "read", status: bearerStatus),
        capabilityRow(id: "spaces.lookup", operation: "spaces", access: "read", status: bearerStatus),
        capabilityRow(id: "spaces.lookupByCreator", operation: "spacesByCreatorIds", access: "read", status: bearerStatus),
        capabilityRow(id: "spaces.search", operation: "searchSpaces", access: "read", status: bearerStatus),
        capabilityRow(id: "spaces.get", operation: "space", access: "read", status: bearerStatus),
        capabilityRow(id: "spaces.buyers", operation: "spaceBuyers", access: "read", status: bearerStatus),
        capabilityRow(id: "spaces.posts", operation: "spacePosts", access: "read", status: bearerStatus),
        capabilityRow(id: "stream.rules", operation: "streamRules", access: "read", status: appBearerPreferredStatus),
        capabilityRow(id: "stream.rules.counts", operation: "streamRuleCounts", access: "read", status: appBearerPreferredStatus),
        capabilityRow(id: "stream.rules.update", operation: "updateStreamRules", access: "write", status: appBearerPreferredStatus),
        capabilityRow(id: "chat.conversations.keys.initialize", operation: "initializeChatConversationKeys", access: "write", status: bearerStatus),
        capabilityRow(id: "chat.group.members.add", operation: "addChatGroupMembers", access: "write", status: bearerStatus),
        capabilityRow(id: "chat.messages.encrypted.create", operation: "sendEncryptedChatMessage", access: "write", status: bearerStatus),
        capabilityRow(id: "chat.conversations.read.mark", operation: "markChatConversationRead", access: "write", status: bearerStatus),
        capabilityRow(id: "chat.conversations.typing.send", operation: "sendChatTypingIndicator", access: "write", status: bearerStatus),
        capabilityRow(id: "chat.group.encrypted.create", operation: "createEncryptedChatGroupConversation", access: "write", status: bearerStatus),
        capabilityRow(id: "chat.group.initialize", operation: "initializeChatGroup", access: "write", status: bearerStatus),
        capabilityRow(id: "chat.media.upload.initialize", operation: "initializeChatMediaUpload", access: "write", status: bearerStatus),
        capabilityRow(id: "chat.media.upload.append", operation: "appendChatMediaUpload", access: "write", status: bearerStatus),
        capabilityRow(id: "chat.media.upload.finalize", operation: "finalizeChatMediaUpload", access: "write", status: bearerStatus),
        capabilityRow(id: "chat.media.download", operation: "downloadChatMedia", access: "read", status: bearerStatus),
        capabilityRow(id: "dm.media.download", operation: "downloadDirectMessageMedia", access: "read", status: bearerStatus)
    ]
}

private func capabilityRow(id: String, operation: String, access: String, status: String) -> [String: Any] {
    return [
        "id": id,
        "operation": operation,
        "access": access,
        "status": status
    ]
}
